version: "3.9"

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=your_email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      # Redirect to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Redirect www to non-www
      - "traefik.http.routers.www-redirect.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.www-redirect.entrypoints=web"
      - "traefik.http.routers.www-redirect.middlewares=redirect-to-https"

  frontend:
    image: your-frontend-image
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`devv.mooo.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: your-backend-image
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`devv.mooo.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  adminer:
    image: adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.devv.mooo.com`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  proxymanager:
  image: jlesage/nginx-proxy-manager
  ports:
    - "8090:80"
    - "4443:443"
  environment:
    - "USER_ID=1000"
    - "GROUP_ID=1000"

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  data:
  letsencrypt:

